-- ============================================================
-- Friendcation — Migration 0004: superseded by 0008_enable_rls.sql
--
-- This file used to hold the RLS gate. It was never applied, and applying it
-- would have broken the app (its trip_members SELECT policy queried
-- trip_members itself — rejected by Postgres as infinite recursion — and it
-- referenced itinerary_item_participants, which only exists from 0006).
-- The corrected gate is 0008_enable_rls.sql; storage policies are in 0007.
--
-- Intentionally a no-op so migrations can still be applied in order.
-- ============================================================
select 1;
